/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.twitter;

import org.mule.tck.AbstractMuleTestCase;

import twitter4j.ResponseList;
import twitter4j.Status;

public class TwitterTestCase extends AbstractMuleTestCase {
    
    public TwitterTestCase() {
        super();
        setStartContext(true);
    }

    public void testGetMessages() throws Exception {
        TwitterConnector connector = new TwitterConnector();
        connector.setMuleContext(muleContext);
        connector.setConsumerKey(System.getProperty("consumer.key"));
        connector.setConsumerSecret(System.getProperty("consumer.secret"));

//        connector.initialise();
//        ResponseList<Status> response = connector.getPublicTimeline();
//        assertTrue(response.size() > 0);
        
    }
}
