/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */

package org.mule.twitter;

import org.mule.tck.AbstractMuleTestCase;

import org.junit.Assert;

import twitter4j.ResponseList;
import twitter4j.Status;
import static org.junit.Assert.*;
public class TwitterTestDriver extends AbstractMuleTestCase
{

    private TwitterConnector connector;

    public TwitterTestDriver()
    {
        super();
        setStartContext(true);
    }

    @Override
    protected void suitePreSetUp() throws Exception
    {
        connector = new TwitterConnector();
        connector.setMuleContext(muleContext);
        connector.setConsumerKey(System.getProperty("consumer.key"));
        connector.setConsumerSecret(System.getProperty("consumer.secret"));
        connector.initialise();
    }

    public void testGetMessages() throws Exception
    {
        Assert.assertNotNull(connector.getCurrentTrends(true));
        // ResponseList<Status> response = connector.getPublicTimeline();
        // assertTrue(response.size() > 0);
    }
}
