/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */

package org.mule.twitter;

import org.mule.api.annotations.callback.SourceCallback;
import org.mule.tck.AbstractMuleTestCase;

import java.util.Arrays;
public class TwitterTestDriver extends AbstractMuleTestCase
{

    private TwitterConnector connector;

    public TwitterTestDriver()
    {
        super();
        setStartContext(true);
    }
    
    @Override
    protected void doSetUp() throws Exception
    {
        connector = new TwitterConnector();
        connector.setMuleContext(muleContext);
        connector.setConsumerKey(System.getenv("consumerKey"));
        connector.setConsumerSecret(System.getenv("consumerSecret"));
        connector.setAccessToken(System.getenv("accessKey"));
        connector.setAccessTokenSecret(System.getenv("accessSecret"));
        connector.initialise();
    }

    public void testGetMessages() throws Exception
    {
        assertNotNull(connector.getCurrentTrends(true));
    }
    
    public void testPublicTimeline() throws Exception
    {
        assertNotNull(connector.getPublicTimeline());
    }
    
    public void testSearchPlaces() throws Exception
    {
        assertNotNull(connector.searchPlaces(50.0, 50.0, null));
    }

    public void ignoreTestFilteredStream() throws Exception
    {
        connector.filteredStream(0, null, Arrays.asList("foo", "bar", "football"), new SourceCallback()
        {
            @Override
            public Void process(Object payload)
            {
                System.out.println(payload);
                return null;
            }
        });
        Thread.sleep(60000);
    }
}
